FROM telegraf       
MAINTAINER  Nsindiso Matshanga (nsinmatsh@gmail.com)
RUN apt-get update 
ENV INFLUX_TOKEN=ydsDKNy45fNoM10GaoToZixwPEW3tf2X7PesGCBs9BTHhKgGfIetqhAZyJRfdVqARmTXzITmC54TirpL2zahyA==
RUN rm /etc/telegraf/telegraf.conf
WORKDIR /etc/telegraf/
ADD telegraf.conf .
EXPOSE  57000
CMD ["telegraf"]
